language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

script: npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/yourbcabus-web
  keep_history: true
  on:
    branch: master
